In [6]:
# 当为array的时候，
# 默认d*f就是对应元素的乘积，
# multiply也是对应元素的乘积，
# dot（d,f）会转化为矩阵的乘积， dot点乘意味着相加，而multiply只是对应元素相乘，不相加


import numpy as np

l1 = np.array([1,2,3])
l2 = np.array([4,5,6])
print(l1*l2)
print(np.multiply(l1,l2))
print(np.dot(l1,l2))

[ 4 10 18]
[ 4 10 18]
32


In [30]:
# 当为mat的时候，默认d*f就是矩阵的乘积，multiply转化为对应元素的乘积，dot（d,f）为矩阵的乘积

l1 = np.array([[1,2,3],[3,4,5], [1,2,5]]) #　2*4
l2 = np.array([[7,8,9], [9,10,11], [11,12,13], [1,2,3]]) # 2 * 4
print(l1)
print(l2)
# print(l1*l2) #不可用
# print(np.multiply(l2,l1)) # 不可用
print(np.dot(l2,l1)) # 矩阵乘

[[1 2 3]
 [3 4 5]
 [1 2 5]]
[[ 7  8  9]
 [ 9 10 11]
 [11 12 13]
 [ 1  2  3]]
[[ 40  64 106]
 [ 50  80 132]
 [ 60  96 158]
 [ 10  16  28]]


In [29]:
l1 = np.array([[1,2,3],[3,4,5], [1,2,5]]) #　2*4
l2 = np.array([[7,8,9], [9,10,11], [11,12,13]]) # 2 * 4
# print(l1)
# print(l2)
print(l1*l2) # 维度相同的情况可用, 对应元素相乘
print(np.multiply(l2,l1)) # 维度相同的情况可用, 对应元素相乘
print(np.dot(l2,l1))

[[ 7 16 27]
 [27 40 55]
 [11 24 65]]
[[ 7 16 27]
 [27 40 55]
 [11 24 65]]
[[ 40  64 106]
 [ 50  80 132]
 [ 60  96 158]]


In [ ]:
# 混合时候的情况，一般不要混合
# 混合的时候默认按照矩阵乘法的, multiply转化为对应元素的乘积，dot（d,f）为矩阵的乘积

In [2]:
# prod
import numpy as np
l = [1,2]
print(np.prod(l))
l = [[1,2],[3,4]]
print(np.prod(l))

2
24
