In [10]:
from keras import backend as K
import numpy as np
import tensorflow as tf

# tensor1 = tf.constant([[1,2],[1,2]])
# tensor2 = tf.constant([[3,4],[3,4]])

# 1 * 3, 4 
# 2

tensor1 = tf.constant([[1],[2]])
tensor2 = tf.constant([[3,4]])

mul = K.dot(tensor1,tensor2)

print(tensor2.shape)
print(mul.shape)
mul1 = K.dot(tensor2, mul) # 1*2  2*2
mul2 = K.dot(mul,  tf.transpose(tensor2))

with tf.Session() as sess:
    output = sess.run(mul)
    print(output)
    output = sess.run(mul1)
    print(output)
    output = sess.run(mul2)
    print(output)

(1, 2)
(2, 2)
[[3 4]
 [6 8]]
[[33 44]]
[[25]
 [50]]
