In [ ]:
# update 张量整体更新
# update_add 通过增加 increment 来更新 x 的值
# update_sub 通过减 decrement 来更新 x 的值
# moving_average_update 计算变量的移动平均值

In [ ]:
# dot
# 求两个张量的乘积。当试图计算两个N阶张量的乘积时

In [2]:
import keras.backend as K
# 张量之间的点积
x = K.placeholder(shape=(2, 3))
y = K.placeholder(shape=(3, 4))
xy = K.dot(x, y)
print(xy)

# 张量之间的点积
x = K.placeholder(shape=(32, 28, 3))
y = K.placeholder(shape=(3, 4))
xy = K.dot(x, y)
print(xy)


Tensor("MatMul:0", shape=(2, 4), dtype=float32)
Tensor("Reshape_2:0", shape=(32, 28, 4), dtype=float32)


In [ ]:
# batch_dot(x, y, axes=None)
# 按批进行张量乘法，该函数用于计算x和y的点积，其中x和y都是成batch出现的数据

In [3]:
x_batch = K.ones(shape=(32, 20, 1))
y_batch = K.ones(shape=(32, 30, 20))
xy_batch_dot = K.batch_dot(x_batch, y_batch, axes=[1, 2])
print(K.int_shape(xy_batch_dot))

(32, 1, 30)


In [ ]:
# gather
# keras.backend.gather(reference, indices)
# 在张量 reference 中检索索引 indices 的元素
# 在张量中找向量
# 参数
# reference: 一个张量
# indices: 索引的整数张量
# 返回
# 与 reference 类型相同的张量

In [ ]:
# max
# 求张量中的最大值
    # keras.backend.max(x, axis=None, keepdims=False)
    # 张量中的最大值。

    # 参数

    # x: 张量或变量。
    # axis: 一个整数，需要在哪个轴寻找最大值。
    # keepdims: 布尔值，是否保留原尺寸。 如果 keepdims 为 False，则张量的秩减 1。 如果 keepdims 为 True，缩小的维度保留为长度 1。
# min
# 求张量中的最小值
# sum
# 在给定轴上计算张量中元素之和
# prod
# 在给定轴上计算张量中元素之积
# cumsum
# 在给定轴上求张量的累积和
# cumprod
# 在给定轴上求张量的累积积
# var
# 在给定轴上计算张量方差
# std
# 在给定轴上求张量元素之标准差
# mean
# 在给定轴上求张量元素之均值
# any
# 按位或，返回数据类型为uint8的张量（元素为0或1）
# all
# 按位与，返回类型为uint8de tensor

In [9]:
import keras.backend as K
a = K.ones((3,4))
b = K.constant([[2,3,4],[5,6,7]])
print(K.eval(b))
# p
print(K.eval(K.max(b)))
print(K.eval(K.max(b, axis=0)))
print(K.eval(K.max(b, axis=1)))

[[2. 3. 4.]
 [5. 6. 7.]]
7.0
[5. 6. 7.]
[4. 7.]


In [ ]:
# argmax 返回指定轴的最大值的索引
# argmin 返回指定轴的最小值的索引
# square 逐元素平方
# abs 逐元素绝对值
# sqrt 逐元素开方
# exp exp(x) 逐元素求自然指数
# log log(x) 逐元素求自然对数
# logsumexp logsumexp(x, axis=None, keepdims=False)
# 在给定轴上计算log(sum(exp()))，该函数在数值稳定性上超过直接计算log(sum(exp()))，可以避免由exp和log导致的上溢和下溢
# round round(x) 逐元素四舍五入
# sign sign(x) 逐元素求元素的符号（+1或-1）
# pow pow(x, a) 逐元素求x的a次方
# clip clip(x, min_value, max_value) 逐元素clip（将超出指定范围的数强制变为边界值）
# equal equal(x, y) 逐元素判相等关系，返回布尔张量
# not_equal not_equal(x, y) 逐元素判不等关系，返回布尔张量
# greater greater(x,y) 逐元素判断x>y关系，返回布尔张量
# greater_equal greater_equal(x,y) 逐元素判断x>=y关系，返回布尔张量
# lesser lesser(x,y) 逐元素判断x<y关系，返回布尔张量
# lesser_equal lesser_equal(x,y) 逐元素判断x<=y关系，返回布尔张量
# maximum maximum(x, y) 逐元素取两个张量的最大值
# minimum minimum(x, y) 逐元素取两个张量的最小值
# sin sin(x) 逐元素求正弦值
# cos cos(x) 逐元素求余弦值