In [ ]:
rnn
rnn(step_function, inputs, initial_states, go_backwards=False, mask=None, constants=None, unroll=False, input_length=None)
在张量的时间维上迭代

参数：

inputs： 形如(samples, time, ...)的时域信号的张量，阶数至少为3
step_function：每个时间步要执行的函数 其参数：
input：形如(samples, ...)的张量，不含时间维，代表某个时间步时一个batch的样本
states：张量列表 其返回值：
output：形如(samples, ...)的张量
new_states：张量列表，与‘states’的长度相同
initial_states：形如(samples, ...)的张量，包含了step_function状态的初始值。
go_backwards：布尔值，若设为True，则逆向迭代序列
mask：形如(samples, time, 1)的二值张量，需要屏蔽的数据元素上值为1
constants：按时间步传递给函数的常数列表
unroll：当使用TensorFlow时，RNN总是展开的。当使用Theano时，设置该值为True将展开递归网络
input_length：使用TensorFlow时不需要此值，在使用Theano时，如果要展开递归网络，必须指定输入序列
返回值：形如(last_output, outputs, new_states)的tuple

last_output：rnn最后的输出，形如(samples, ...)
outputs：形如(samples, time, ...)的张量，每个在[s,t]点的输出对应于样本s在t时间的输出
new_states: 列表，其元素为形如(samples, ...)的张量，代表每个样本的最后一个状态

In [ ]:
relu
relu(x, alpha=0.0, max_value=None)
修正线性单元

参数：

alpha：负半区斜率
max_value: 饱和门限


In [ ]:
elu
elu(x, alpha=1.0)
指数线性单元

参数：

x：输入张量
alpha: 标量


In [3]:
# softmax
# softmax(x)
# 返回张量的softmax值
import tensorflow as tf
import keras.backend as K
a = tf.constant([[1,2,3],[1,2,3],[1,1,1]], dtype='float32')

with tf.Session() as sess:
    print(sess.run(K.softmax(a)))


[[0.09003057 0.24472848 0.66524094]
 [0.09003057 0.24472848 0.66524094]
 [0.33333334 0.33333334 0.33333334]]


In [ ]:
softplus
softplus(x)
返回张量的softplus值


In [ ]:
softsign
softsign(x)
返回张量的softsign值

In [ ]:
categorical_crossentropy
categorical_crossentropy(output, target, from_logits=False)
计算输出张量和目标张量的Categorical crossentropy（类别交叉熵），目标张量与输出张量必须shape相同


In [ ]:
sparse_categorical_crossentropy
sparse_categorical_crossentropy(output, target, from_logits=False)
计算输出张量和目标张量的Categorical crossentropy（类别交叉熵），目标张量必须是整型张量


In [ ]:
binary_crossentropy
binary_crossentropy(output, target, from_logits=False)
计算输出张量和目标张量的交叉熵

In [ ]:
sigmoid
sigmoid(x)
逐元素计算sigmoid值

In [ ]:
hard_sigmoid
hard_sigmoid(x)
该函数是分段线性近似的sigmoid，计算速度更快

In [ ]:
tanh
tanh(x)
逐元素计算sigmoid值

In [ ]:
dropout
dropout(x, level, seed=None)
随机将x中一定比例的值设置为0，并放缩整个tensor

参数：

x：张量
level：x中设置成0的元素比例
seed：随机数种子
l2_normalize
l2_normalize(x, axis)
在给定轴上对张量进行L2范数规范化

In [ ]:
l2_normalize
keras.backend.l2_normalize(x, axis=None)
在指定的轴使用 L2 范式 标准化一个张量。

参数

x: 张量或变量。
axis: 需要执行标准化的轴。
返回

一个张量。

In [ ]:
in_top_k
in_top_k(predictions, targets, k)
判断目标是否在predictions的前k大值位置

参数：

predictions：预测值张量, shape为(batch_size, classes), 数据类型float32
targets：真值张量, shape为(batch_size,),数据类型为int32或int64
k：整数

In [ ]:
conv1d
conv1d(x, kernel, strides=1, border_mode='valid', image_shape=None, filter_shape=None)
1D卷积

参数：

kernel：卷积核张量
strides：步长，整型
border_mode：“same”，“valid”之一的字符串

In [ ]:
conv2d
conv2d(x, kernel, strides=(1, 1), border_mode='valid', dim_ordering='th', image_shape=None, filter_shape=None)
2D卷积

参数：

kernel：卷积核张量
strides：步长，长为2的tuple
border_mode：“same”，“valid”之一的字符串
dim_ordering：“tf”和“th”之一，维度排列顺序

In [ ]:
deconv2d
deconv2d(x, kernel, output_shape, strides=(1, 1), border_mode='valid', dim_ordering='th', image_shape=None, filter_shape=None)
2D反卷积（转置卷积）

参数：

x：输入张量
kernel：卷积核张量
output_shape: 输出shape的1D的整数张量
strides：步长，tuple类型
border_mode：“same”或“valid”
dim_ordering：“tf”或“th”

In [ ]:
conv3d
conv3d(x, kernel, strides=(1, 1, 1), border_mode='valid', dim_ordering='th', volume_shape=None, filter_shape=None)
3D卷积

参数：

x：输入张量
kernel：卷积核张量
strides：步长，tuple类型
border_mode：“same”或“valid”
dim_ordering：“tf”或“th”

In [ ]:
pool2d
pool2d(x, pool_size, strides=(1, 1), border_mode='valid', dim_ordering='th', pool_mode='max')
2D池化

参数：

pool_size：含有两个整数的tuple，池的大小
strides：含有两个整数的tuple，步长
border_mode：“same”，“valid”之一的字符串
dim_ordering：“tf”和“th”之一，维度排列顺序
pool_mode: “max”，“avg”之一，池化方式

In [ ]:
pool3d
pool3d(x, pool_size, strides=(1, 1, 1), border_mode='valid', dim_ordering='th', pool_mode='max')
3D池化

参数：

pool_size：含有3个整数的tuple，池的大小
strides：含有3个整数的tuple，步长
border_mode：“same”，“valid”之一的字符串
dim_ordering：“tf”和“th”之一，维度排列顺序
pool_mode: “max”，“avg”之一，池化方式

In [ ]:
local_conv1d
keras.backend.local_conv1d(inputs, kernel, kernel_size, strides, data_format=None)
在不共享权值的情况下，运用 1D 卷积。

参数

inputs: 3D 张量，尺寸为 (batch_size, steps, input_dim)
kernel: 卷积的非共享权重, 尺寸为 (output_items, feature_dim, filters)
kernel_size: 一个整数的元组， 指定 1D 卷积窗口的长度。
strides: 一个整数的元组， 指定卷积步长。
data_format: 数据格式，channels_first 或 channels_last。
返回

运用不共享权重的 1D 卷积之后的张量，尺寸为 (batch_size, output_length, filters)。

异常

ValueError: 如果 data_format 既不是 channels_last 也不是 channels_first。

In [ ]:
local_conv2d
keras.backend.local_conv2d(inputs, kernel, kernel_size, strides, output_shape, data_format=None)
在不共享权值的情况下，运用 2D 卷积。

参数

inputs: 如果 data_format='channels_first'， 则为尺寸为 (batch_size, filters, new_rows, new_cols) 的 4D 张量。 如果  data_format='channels_last'， 则为尺寸为 (batch_size, new_rows, new_cols, filters) 的 4D 张量。
kernel: 卷积的非共享权重, 尺寸为 (output_items, feature_dim, filters)
kernel_size: 2 个整数的元组， 指定 2D 卷积窗口的宽度和高度。
strides: 2 个整数的元组， 指定 2D 卷积沿宽度和高度方向的步长。
output_shape: 元组 (output_row, output_col) 。
data_format: 数据格式，channels_first 或 channels_last。
返回

一个 4D 张量。

如果 data_format='channels_first'，尺寸为 (batch_size, filters, new_rows, new_cols)。
如果 data_format='channels_last'，尺寸为 (batch_size, new_rows, new_cols, filters)
异常

ValueError: 如果 data_format 既不是 channels_last 也不是 channels_first。