# 类型转化 Casting

In [ ]:
# tf.shape()
# tf.size()
# tf.rank()

In [10]:
# tf.reshape()
import tensorflow as tf
a1 = tf.constant([[1,2,3,4,5],[5,6,7,8,9]])
a2 = tf.reshape(a1, [-1,1])
# a3 = tf.reshape(a1, [3,3])
a4 = tf.reshape(a2, [5,2])

with tf.Session() as sess:
    print(a1.shape)
    print(sess.run(a1))
    print(a2.shape)
    print(sess.run(a2))
#     sess.run(a3)
    print(a4.shape)
    print(sess.run(a4))

(2, 5)
[[1 2 3 4 5]
 [5 6 7 8 9]]
(10, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [5]
 [6]
 [7]
 [8]
 [9]]
(5, 2)
[[1 2]
 [3 4]
 [5 5]
 [6 7]
 [8 9]]


In [ ]:
# tf.expand_dims()

# 形状操作 Shapes and Shaping

# 切片与合并 Slicing and Joining