In [3]:
import tensorflow as tf
 
# t1 = tf.Variable([1,2,3,4,5])
t1 = tf.constant([1,2,3,4,5])
t2 = tf.cast(t1,dtype=tf.float32)
 
print('t1: {}'.format(t1))
print('t2: {}'.format(t2))
 
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(t1))
    print(sess.run(t2))

t1: Tensor("Const_1:0", shape=(5,), dtype=int32)
t2: Tensor("Cast_2:0", shape=(5,), dtype=float32)
[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [4]:
import tensorflow as tf
a1 = tf.Variable([1,2,3,4,5])
a2 = tf.cast(a1, dtype=tf.float32)
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(a1))
print(sess.run(a2))


[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [18]:
a = tf.constant([1,0,0,1,1])
b = tf.cast(a,dtype=tf.bool)
sess = tf.Session()
sess.run(tf.initialize_all_variables())
print(sess.run(b))

[ True False False  True  True]


In [30]:
import tensorflow as tf
a1 = tf.Variable([1,2,3,4,5])
a2 = tf.cast(a1, dtype=tf.float32)
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(a1))
print(sess.run(a2))

[1 2 3 4 5]
[0. 0. 0. 0. 0.]


In [5]:
import tensorflow as tf
a1 = tf.Variable([1,2,3,4,5])
a2 = tf.cast(a1, dtype=tf.float32)
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(a1))
print(sess.run(a2))

[1 2 3 4 5]
[1. 2. 3. 4. 5.]
