In [1]:
import tensorflow as tf
sess = tf.Session()

/opt/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [4]:
# Tensor 的定义
# 属性: name, shape, type
# 常量
a = tf.constant([1.0,2.0], name='a')
# 变量 Create two variables.
weights = tf.Variable(tf.random_normal([4, 3], stddev=0.35),
                      name="weights")
biases = tf.Variable(tf.zeros([3]), name="biases")

init_op = tf.initialize_all_variables()

with tf.Session() as sess:
    sess.run(init_op)
    print(sess.run(weights))
    print(sess.run(biases))

[[ 0.52872086  0.13738121 -0.02748405]
 [ 0.12851319  0.63279653  0.54203308]
 [-0.38942128  0.33467355 -0.07482897]
 [ 0.39736488  0.04524826  0.5549919 ]]
[ 0.  0.  0.]


In [3]:
sess = tf.Session()
## Tensorflow 数学计算和逻辑计算
ts1=tf.constant(1.0,shape=[2,2])  
ts2=tf.Variable(tf.random_normal([2,2]))  
sess.run(tf.global_variables_initializer())  
ts_add1=tf.add(ts1,ts2,name=None)  
ts_add2=ts1+ts2       #二者等价  

# print(ts_add1.eval())
# print(ts_add2.eval())
print(sess.run(ts_add1))

[[ 0.68465811 -1.58034468]
 [ 0.15035874  0.92607343]]


In [4]:
import tensorflow as tf  
a = tf.constant(5.0)  
b = tf.constant(6.0)  
c = a * b  
with tf.Session():  
  # We can also use 'c.eval()' here.  
  print(c.eval())  

30.0


In [6]:
# tensorflow 和 numpy 在 显示上的区别
ta = tf.zeros((2,2))
print(ta)
# print(ta.eval()) 无效

Tensor("zeros_1:0", shape=(2, 2), dtype=float32)


In [ ]:
# 加法

In [ ]:
# 乘法
# Tensor
# A * B 表示按元素计算
# tf.mul(A,B)  表示按元素计算
tf.matmul(A,B) 表示矩阵乘法
# Numpy
# A * B 表示按元素计算
# dot(A,B)表示矩阵乘法