In [7]:
from keras import backend as K
from keras.layers import Multiply, Flatten
import numpy as np
import tensorflow as tf
tensor1 = tf.constant([[[1],[1],[2],[2]],
                       [[3],[3],[4],[4]],
                       [[5],[5],[6],[6]],
                      ])
tensor2 = tf.constant([[2,2]])
# mul = Multiply()([tensor1,tensor2])
fla = Flatten()(tensor1)

with tf.Session() as sess:
    output = sess.run(fla)
    print(output)

[[1 1 2 2]
 [3 3 4 4]
 [5 5 6 6]]
