In [1]:
import tensorflow as tf

temp = tf.range(0,10)*10 + tf.constant(1,shape=[10])
temp2 = tf.gather(temp,[1,5,9])

with tf.Session() as sess:
    print(sess.run(temp))
    print(sess.run(temp2))

/opt/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
/opt/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


[ 1 11 21 31 41 51 61 71 81 91]
[11 51 91]


In [5]:
import tensorflow as tf
tmp0 = tf.Variable([90,91], dtype=tf.float32)

tmp1 = tf.Variable([[1,2],
                     [3,4],
                     [5,6]], dtype=tf.float32)
tmp3 = tf.scatter_update(tmp1, 2, tmp0)

tmp4 = tf.gather(tmp3,[1], axis = 0)
print(tmp4.shape[1:])
tmp5 = tf.reshape(tmp4, tmp4.shape[1:])

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(tmp3))
    print(sess.run(tmp4))
    print(sess.run(tmp5))
#     print(sess.run(tmp2))
    
    

(2,)
[[ 1.  2.]
 [ 3.  4.]
 [90. 91.]]
[[3. 4.]]
[3. 4.]
