In [1]:
import numpy as np

### 均匀分布
+ np.random.uniform(low=0.0, high=1.0, size=None):
+ 从一个均匀分布[low,high)中随机采样，注意定义域是左闭右开，即包含low，不包含high.

In [23]:
np.random.uniform(2,3,size=(2,2))

array([[2.71119437, 2.98142228],
       [2.89461078, 2.46822099]])

### 正太分布
+ np.random.normal(loc=0.0, scale=1.0, size=None):
+ 正态分布

In [24]:
np.random.normal(size=(2,3))

array([[ 1.57752914,  1.1832134 , -1.04544672],
       [-0.23788798, -1.36250569, -1.18003206]])

### numpy.random.rand(d0,d1,…,dn)
+ rand函数根据给定维度生成[0,1)之间的数据，包含0，不包含1
+ dn表格每个维度
+ 返回值为指定维度的array

In [2]:
np.random.rand(3,2)

array([[0.77519909, 0.82824485],
       [0.32614085, 0.81848333],
       [0.1002229 , 0.13739844]])

In [3]:
np.random.rand(3,2,2)

array([[[0.27879286, 0.25270632],
        [0.78298399, 0.18208875]],

       [[0.98722879, 0.98407517],
        [0.74173717, 0.44400393]],

       [[0.21091472, 0.88837361],
        [0.37729933, 0.40847347]]])

### numpy.random.randn(d0,d1,…,dn)
+ randn函数返回一个或一组样本，具有标准正态分布。
+ dn表格每个维度
+ 返回值为指定维度的array
+ 标准正态分布介绍
    + 标准正态分布—-standard normal distribution
    + 标准正态分布又称为u分布，是以0为均值、以1为标准差的正态分布，记为N（0，1）

### numpy.random.randint(low, high=None, size=None, dtype=’l’)
+ 返回随机整数，范围区间为[low,high），包含low，不包含high
+ 参数：low为最小值，high为最大值，size为数组维度大小，dtype为数据类型，默认的数据类型是np.int
+ high没有填写时，默认生成随机数的范围是[0，low)

In [4]:
np.random.randint(1,size=5) # 返回[0,1)之间的整数，所以只有0

array([0, 0, 0, 0, 0])

In [5]:
np.random.randint(1,10,size=5) # 返回[0,1)之间的整数，所以只有0

array([1, 2, 3, 6, 5])

In [6]:
np.random.randint(1,10, size=(2,3)) # 返回[0,1)之间的整数，所以只有0

array([[1, 6, 9],
       [1, 2, 4]])

### 生成[0,1)之间的浮点数
+ numpy.random.random_sample(size=None)
+ numpy.random.random(size=None)
+ numpy.random.ranf(size=None)
+ numpy.random.sample(size=None)

In [7]:
print('-----------random_sample--------------')
print(np.random.random_sample(size=(2,2)))
print('-----------random--------------')
print(np.random.random(size=(2,2)))
print('-----------ranf--------------')
print(np.random.ranf(size=(2,2)))
print('-----------sample--------------')
print(np.random.sample(size=(2,2)))

-----------random_sample--------------
[[0.56691379 0.32996418]
 [0.08253883 0.4076677 ]]
-----------random--------------
[[0.04327094 0.03483217]
 [0.62287854 0.16635707]]
-----------ranf--------------
[[0.36024728 0.51642917]
 [0.37898007 0.78412046]]
-----------sample--------------
[[0.98866129 0.49887959]
 [0.73710695 0.29226851]]


### numpy.random.choice()
+ numpy.random.choice(a, size=None, replace=True, p=None)
+ 从给定的一维数组中生成随机数
+ 参数： a为一维数组类似数据或整数；size为数组维度；p为数组中的数据出现的概率
+ a为整数时，对应的一维数组为np.arange(a)

In [12]:
np.random.choice(5, 3, replace=False)
# 当replace为False时，生成的随机数不能有重复的数值

array([0, 3, 2])

In [13]:
np.random.choice(5, 3)

array([1, 1, 0])

### numpy.random.seed()
+ np.random.seed()的作用：使得随机数据可预测。
+ 当我们设置相同的seed，每次生成的随机数相同。如果不设置seed，则每次会生成不同的随机数

In [9]:
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [10]:
np.random.seed(1676)
np.random.rand(5)

array([0.39983389, 0.29426895, 0.89541728, 0.71807369, 0.3531823 ])

In [11]:
np.random.seed(1676)
np.random.rand(5)

array([0.39983389, 0.29426895, 0.89541728, 0.71807369, 0.3531823 ])

### numpy.random.shuffle(x)
+ 对X进行重排序，如果X为多维数组，只沿第一条轴洗牌，输出为None

In [20]:
#numpy.random.shuffle(x)
import numpy as np
list1 = [1,2,3,4,5]
print(np.random.shuffle(list1)) # 一维数组输出为None
print(list1) # list1 原始的list 会被修改
arr = np.arange(9).reshape(3,3)
print(arr)
print(np.random.shuffle(arr))#对于多维数组，只沿着第一条轴打乱顺序
print(arr)

None
[3, 4, 2, 1, 5]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
None
[[3 4 5]
 [6 7 8]
 [0 1 2]]


### numpy.random.permutation(x)
+ 与numpy.random.shuffle(x)函数功能相同，两者区别：peumutation(x)不会修改X的顺序。

In [17]:
#numpy.random.permutation(x)
import numpy as np
#x=5
print(np.random.permutation(5))#生成一个range(5)随机顺序的数组
#x为列表或元组
list1 = [1,2,3,4]
print(np.random.permutation(list1))#array([2, 1, 4, 3])
#list1#[1, 2, 3, 4]
#x为数组
arr = np.arange(9)
print(np.random.permutation(arr))
arr2 = np.arange(9).reshape(3,3)
print(arr2)

[1 4 2 0 3]
[3 4 1 2]
[4 0 5 7 1 2 3 8 6]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
