In [2]:
b = K.random_uniform_variable(shape=(3, 4), low=0, high=1) # 均匀分布
c = K.random_normal_variable(shape=(3, 4), mean=0, scale=1) # 高斯分布
d = K.random_normal_variable(shape=(3, 4), mean=0, scale=1)
print(K.eval(b))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [1]:
import keras.backend as K
x = K.random_uniform_variable(shape=(2, 2), low=0, high=100)
y = K.random_uniform_variable(shape=(2, 2), low=0, high=100)
xy = K.dot(x, y)
K.int_shape(xy)
print(K.eval(x))
print(K.eval(y))
# print(K.eval(xy))

/opt/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
/opt/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


[[0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]]


In [3]:
"""Multiplies 2 tensors (and/or variables) and returns a *tensor*.

When attempting to multiply a nD tensor
with a nD tensor, it reproduces the Theano behavior.
(e.g. `(2, 3) * (4, 3, 5) -> (2, 4, 5)`)

# Arguments
    x: Tensor or variable.
    y: Tensor or variable.

# Returns
    A tensor, dot product of `x` and `y`.

# Examples
```python
    # dot product between tensors
    >>> x = K.placeholder(shape=(2, 3))
    >>> y = K.placeholder(shape=(3, 4))
    >>> xy = K.dot(x, y)
    >>> xy
    <tf.Tensor 'MatMul_9:0' shape=(2, 4) dtype=float32>
```

```python
    # dot product between tensors
    >>> x = K.placeholder(shape=(32, 28, 3))
    >>> y = K.placeholder(shape=(3, 4))
    >>> xy = K.dot(x, y)
    >>> xy
    <tf.Tensor 'MatMul_9:0' shape=(32, 28, 4) dtype=float32>
```

```python
    # Theano-like behavior example
    >>> x = K.random_uniform_variable(shape=(2, 3), low=0, high=1)
    >>> y = K.ones((4, 3, 5))
    >>> xy = K.dot(x, y)
    >>> K.int_shape(xy)
    (2, 4, 5)
```
"""

"Multiplies 2 tensors (and/or variables) and returns a *tensor*.\n\nWhen attempting to multiply a nD tensor\nwith a nD tensor, it reproduces the Theano behavior.\n(e.g. `(2, 3) * (4, 3, 5) -> (2, 4, 5)`)\n\n# Arguments\n    x: Tensor or variable.\n    y: Tensor or variable.\n\n# Returns\n    A tensor, dot product of `x` and `y`.\n\n# Examples\n```python\n    # dot product between tensors\n    >>> x = K.placeholder(shape=(2, 3))\n    >>> y = K.placeholder(shape=(3, 4))\n    >>> xy = K.dot(x, y)\n    >>> xy\n    <tf.Tensor 'MatMul_9:0' shape=(2, 4) dtype=float32>\n```\n\n```python\n    # dot product between tensors\n    >>> x = K.placeholder(shape=(32, 28, 3))\n    >>> y = K.placeholder(shape=(3, 4))\n    >>> xy = K.dot(x, y)\n    >>> xy\n    <tf.Tensor 'MatMul_9:0' shape=(32, 28, 4) dtype=float32>\n```\n\n```python\n    # Theano-like behavior example\n    >>> x = K.random_uniform_variable(shape=(2, 3), low=0, high=1)\n    >>> y = K.ones((4, 3, 5))\n    >>> xy = K.dot(x, y)\n    >>> K.in